// <auto-generated />
using System;
using FreeMountainTest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FreeMountainTest.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211006181220_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FreeMountainTest.Models.Campaign", b =>
                {
                    b.Property<string>("Mfid")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("MFID");

                    b.Property<string>("AlertNum")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ALERT_NUM");

                    b.Property<string>("AllowRentalList")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("ALLOW_RENTAL_LIST");

                    b.Property<string>("AmazonCode")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("AMAZON_CODE");

                    b.Property<string>("AmlUniverse")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("AML_UNIVERSE");

                    b.Property<string>("AvRequired")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("AV_REQUIRED");

                    b.Property<string>("Channel")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("CHANNEL");

                    b.Property<string>("Client")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("CLIENT");

                    b.Property<string>("CustomerSearch")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("CUSTOMER_SEARCH");

                    b.Property<DateTime?>("DtsDate")
                        .HasColumnType("datetime")
                        .HasColumnName("DTS_DATE");

                    b.Property<string>("EmailSubject")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("EMAIL_SUBJECT");

                    b.Property<DateTime?>("ExtractDate")
                        .HasColumnType("datetime")
                        .HasColumnName("EXTRACT_DATE");

                    b.Property<string>("ExtractSql")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EXTRACT_SQL");

                    b.Property<string>("ExtractView")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("EXTRACT_VIEW");

                    b.Property<string>("HtmlLocation")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("HTML_LOCATION");

                    b.Property<string>("Isconsumer")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("ISCONSUMER");

                    b.Property<string>("Isinfluencer")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("ISINFLUENCER");

                    b.Property<string>("MfidDescription")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MFID_DESCRIPTION");

                    b.Property<string>("PrintVendor")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("PRINT_VENDOR");

                    b.Property<string>("Promotion")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)")
                        .HasColumnName("PROMOTION");

                    b.Property<string>("Recurrance")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("RECURRANCE");

                    b.Property<string>("RevisionNum")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("REVISION_NUM");

                    b.Property<int?>("SeedList")
                        .HasColumnType("int")
                        .HasColumnName("SEED_LIST");

                    b.Property<int>("SeqNum")
                        .HasColumnType("int")
                        .HasColumnName("SEQ_NUM");

                    b.Property<string>("Status")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("STATUS");

                    b.Property<string>("Wave")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("WAVE");

                    b.Property<string>("WorkFlow")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("WORK_FLOW");

                    b.HasKey("Mfid");

                    b.ToTable("CAMPAIGNS");
                });

            modelBuilder.Entity("FreeMountainTest.Models.Response", b =>
                {
                    b.Property<string>("ResponseCode")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("RESPONSE_CODE");

                    b.Property<string>("Channel")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("CHANNEL");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime")
                        .HasColumnName("END_DATE");

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnType("datetime")
                        .HasColumnName("LAST_UPDATE_DATE");

                    b.Property<string>("Promotion")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PROMOTION");

                    b.Property<string>("ResponseDescription")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("RESPONSE_DESCRIPTION");

                    b.Property<string>("ResponseType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("RESPONSE_TYPE");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime")
                        .HasColumnName("START_DATE");

                    b.Property<string>("Status")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("STATUS");

                    b.HasKey("ResponseCode");

                    b.ToTable("RESPONSES");
                });
#pragma warning restore 612, 618
        }
    }
}
